name: lazy_load_indexed_stack
description: A package that extends IndexedStack to allow for lazy loading.
version: 1.2.0
homepage: https://github.com/okaryo/lazy_load_indexed_stack
repository: https://github.com/okaryo/lazy_load_indexed_stack

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
