name: lazy_load_indexed_stack
description: A package that extends IndexedStack to allow for lazy loading.
version: 0.1.2
homepage: https://github.com/okaryo/lazy_load_indexed_stack
repository: https://github.com/okaryo/lazy_load_indexed_stack

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
