name: Test and Lint

on:
  push:

env:
  FLUTTER_VERSION: 3.10.0

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
      - name: Run pub get
        run: flutter pub get
      - name: Run test
        run: flutter test

  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
    - name: Run pub get
      run: flutter pub get
    - name: Run analyze
      run: flutter analyze
